DO $$
DECLARE
  next_public_id bigint;
BEGIN
  LOCK TABLE "public"."contents" IN ACCESS EXCLUSIVE MODE;

  ALTER TABLE "public"."contents" RENAME COLUMN "slug" TO "public_id";
  ALTER TABLE "public"."contents" ALTER COLUMN "public_id" TYPE integer USING "public_id"::integer;
  ALTER INDEX "public"."contents_slug_key" RENAME TO "contents_public_id_key";
  ALTER TABLE "public"."contents" ALTER COLUMN "public_id" ADD GENERATED BY DEFAULT AS IDENTITY;

  SELECT COALESCE(MAX("public_id")::bigint + 1, 1)
  INTO next_public_id
  FROM "public"."contents";

  EXECUTE format(
    'ALTER TABLE "public"."contents" ALTER COLUMN "public_id" RESTART WITH %s',
    next_public_id
  );
END;
$$;
